name: fact-check-pipeline
on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "YYYY-MM-DD"
        required: false
      end_date:
        description: "YYYY-MM-DD"
        required: false
  schedule:
    - cron: "30 17 * * *"
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      HTTP_PROXY:  ${{ secrets.HTTP_PROXY }}
      HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
      ALL_PROXY:   ${{ secrets.ALL_PROXY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt snscrape
      - name: Window
        run: |
          START="${{ github.event.inputs.start_date }}"
          END="${{ github.event.inputs.end_date }}"
          [ -z "$START" ] && START="2024-09-01"
          [ -z "$END" ] && END="2025-10-01"
          echo "PIPELINE_START=$START" >> $GITHUB_ENV
          echo "PIPELINE_END=$END"   >> $GITHUB_ENV
      - name: Fetch
        run: |
          python scripts/fetch_x.py --config config.yaml
          test -n "$(ls -1 data/raw/*.jsonl 2>/dev/null || true)" || { echo "NO_RAW_FILES"; exit 1; }
          BYTES=$(wc -c data/raw/*.jsonl | tail -1 | awk '{print $1}')
          [ "$BYTES" -gt 0 ] || { echo "NO_DATA_BYTES"; exit 1; }
      - name: Build & Viz
        run: |
          python scripts/build_metrics.py --config config.yaml
          python scripts/survival_viz.py  --config config.yaml
          python scripts/cox_model.py     --config config.yaml || true
          python scripts/more_viz.py      || true
          python scripts/update_ppt.py    --config config.yaml || true
          python scripts/update_report.py --config config.yaml || true
      - uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.run_id }}
          path: |
            analysis/**
            outputs/**
            data/clean/**
            data/raw/**
          if-no-files-found: error
      - name: Commit results branch
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B results
          git add -A
          git commit -m "auto: results $(date -u +%F)" || true
          git push -f origin results